# Generated by Django 2.1.2 on 2018-10-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauthServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcode_log',
            name='redirect_uri',
            field=models.URLField(verbose_name=''),
        ),
    ]
